Feature/#41
petshop-system/petshop-api pull request #63
Opened 2023-12-26 01:46 UTC by lechitz

2023-12-26 01:52 UTC, lechitz commented on application/service/phone_test.go
> +package service
ainda vou subir o teste

2023-12-26 21:02 UTC, MatheusFerreiraZx approved these changes

2023-12-27 03:23 UTC, MaironCosta commented on application/service/phone.go
> +	err := utils.ValidateCodeAreaNumber(phone.CodeArea)
Poderia fazer essa checagem em menos linhas.

```
if err := utils.ValidateCodeAreaNumber(phone.CodeArea); err != nil {
		return domain.PhoneDomain{}, nil
}
```

2023-12-27 03:28 UTC, MaironCosta commented on application/utils/utils.go
> +	dddList := []string{
Poderia fazer com map, desta forma evitaria o "for".

https://www.freecodecamp.org/portuguese/news/notacao-big-o-explicada-com-exemplos/

2023-12-27 03:29 UTC, MaironCosta requested changes
Comentários adicionados.

2023-12-28 00:10 UTC, MaironCosta commented on application/service/phone.go
> +	err := utils.ValidatePhoneNumber(phone.PhoneType, phone.Number)
Poderia ser igual ao if anterior.

2023-12-28 00:13 UTC, MaironCosta commented on application/utils/utils.go
> +	dddList := map[string]bool{
Muito melhor! 😉👍

2023-12-28 00:20 UTC, MaironCosta approved these changes

2023-12-28 01:40 UTC, merged

2023-12-28 02:21 UTC, MaironCosta commented on application/utils/utils.go
> +	landLinePhoneLen := 8
Essas duas variáveis poderiam estar dentro de seus swtich-case correspondentes. Neste caso, a alocação de memória seria mais curta (tempo de vida da variável alocada em memória) e somente utilizada quando necessário.